// Code generated by goctl. DO NOT EDIT.
// goctl {{.Version}}

{{range $i, $t := .Types}}
{{if gt (len $t.Members) 0}}export type {{$t.TypeName}} = { {{range $j, $m := $t.Members}}
    {{$m.PropertyName}}{{$m.OptionalTag}}: {{$m.PropertyType}};{{if $m.Comment}} // {{$m.Comment}}{{end}}{{end}}
};{{end}}
{{range $j, $s := $t.SubTypes}}
export type {{$s.TypeName}} = { {{range $j, $m := $s.Members}}
    {{$m.PropertyName}}{{$m.OptionalTag}}: {{$m.PropertyType}};{{if $m.Comment}} // {{$m.Comment}}{{end}}{{end}}
};
{{end}}{{end}}